services:
  threadwell-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: threadwell
    ports:
      - "8080:8080"
    #volumes:
    #  - ./data:/app/data
    environment:
      - STORAGE_TYPE=memory
      - STORAGE_PATH=/app/data/threadwell.db

  threadwell-webui:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - threadwell-backend